/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-07-22 10:07:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.*;
import jakarta.servlet.*;

public final class AboutusLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Do NOT redeclare 'session'; it's already provided by JSP
    if (session == null || session.getAttribute("username") == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"/>\r\n");
      out.write("    <title>About Us</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    body{\r\n");
      out.write("        background-image: url(images/gradient-connection-background_23-2150462053.avif);\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-size: 1400px 700px;\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("    }\r\n");
      out.write("    body {\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-size: 1380px 750px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ol {\r\n");
      out.write("        background-size: 40px;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  li {\r\n");
      out.write("            display: inline;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: 124px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: aqua;\r\n");
      out.write("            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a:hover {\r\n");
      out.write("            background-color: rgb(53, 61, 53);\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-width: 2px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    img {\r\n");
      out.write("        width: 70px;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("    }\r\n");
      out.write("    .title{\r\n");
      out.write("        width: 650px;\r\n");
      out.write("    }\r\n");
      out.write("    h1{\r\n");
      out.write("        color: aqua;\r\n");
      out.write("    }\r\n");
      out.write("    .title{\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    h4{\r\n");
      out.write("        margin-top: 0px;\r\n");
      out.write("        color: blanchedalmond;\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("    }\r\n");
      out.write("    p{\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        color:ghostwhite;\r\n");
      out.write("    }\r\n");
      out.write("    .leftcontent{\r\n");
      out.write("        width: 550px;\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        margin-left: -680px;\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    .rightcontent{\r\n");
      out.write("        width: 550px;\r\n");
      out.write("        margin-left: 700px;\r\n");
      out.write("        margin-top: -305px;\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    .footer{\r\n");
      out.write("            width: 1275px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background-color: grey;\r\n");
      out.write("    }\r\n");
      out.write("    .wrapper{\r\n");
      out.write("            margin-left: 450px;\r\n");
      out.write("            margin-top: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        .navigate{\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <img src=\"images/249.jpg\" alt=\"\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><a href=\"HomeLogin.jsp\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"ProductLogin.jsp\">Products</a></li>\r\n");
      out.write("                        <li><a href=\"AboutusLogin.jsp\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"ContactLogin.jsp\">Contact</a></li>\r\n");
      out.write("                        <li><a href=\"Logout\">Logout</a></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <center>\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("    <h1>About Us</h1>\r\n");
      out.write("    <h4>Fueling Your Game. Every Day.</h4>\r\n");
      out.write("    <p>At Regis Sports, we’re more than just a sports store — we’re a team of athletes, fans, and fitness junkies who live and breathe the game. Whether you're training for your next marathon, scoring goals on the weekend, or just looking to level up your gear, we’ve got your back.</p>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("<div class=\"leftcontent\"><center>\r\n");
      out.write("    <h4 style=\"font-size: 35px;\">Born from Passion</h4></center><br>\r\n");
      out.write("    <p>What started as a small idea among friends who couldn’t find high-quality gear at fair prices has grown into a full-blown movement. We set out to create a place where anyone — from weekend warriors to elite athletes — can find the best in performance wear, gear, and accessories without the hassle.Our Moto is \"You'll never Experience Unless You try\"</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"rightcontent\"><center>\r\n");
      out.write("    <h4 >Our Mission</h4></center><br>\r\n");
      out.write("    <p>1.Empower every athlete with premium-quality gear.<br>\r\n");
      out.write("        2.Inspire a lifestyle of health, fitness, and determination.<br>\r\n");
      out.write("        3.Build a community that shares passion for sports and wellness.<br>\r\n");
      out.write("        4.Offer fair prices without compromising on quality.\r\n");
      out.write("        </p><br><br><br><br>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Facebook</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Twitter</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Instagram</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-github\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Github</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>YouTube</span>\r\n");
      out.write("        </a><br><br><br><br>\r\n");
      out.write("        <div class=\"navigate\">\r\n");
      out.write("            <pre><a href=\"Home.jsp\">Home</a>         <a href=\"contact.jsp\">Contactus</a>          <a href=\"login.jsp\">Login</a>            <a href=\"register.jsp\">Register</a></pre>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
