/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-07-22 10:07:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.*;
import jakarta.servlet.*;

public final class ContactLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Do NOT redeclare 'session'; it's already provided by JSP
    if (session == null || session.getAttribute("username") == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    String username = (String) session.getAttribute("username");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Contact Us</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url(images/loginbg.avif);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: 1380px 750px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ol {\r\n");
      out.write("            background-size: 40px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("         li {\r\n");
      out.write("            display: inline;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: 115px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: aqua;\r\n");
      out.write("            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a:hover {\r\n");
      out.write("            background-color: rgb(53, 61, 53);\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-width: 2px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        img {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .content {\r\n");
      out.write("            background-image: url(images/3d-render-concept-phone-receiver-3d-art-design-illustration.jpg);\r\n");
      out.write("            background-size: 950px 520px;\r\n");
      out.write("            padding: 18px 20px;\r\n");
      out.write("            width: 900px;\r\n");
      out.write("            height: 480px;\r\n");
      out.write("            border: aqua solid;\r\n");
      out.write("            margin-left: 190px;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("         input{\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        button{\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 255px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover{\r\n");
      out.write("            background-color: aqua;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            margin-left: 120px;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .address {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <img src=\"images/249.jpg\" alt=\"\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                         <li><a href=\"HomeLogin.jsp\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"ProductLogin.jsp\">Products</a></li>\r\n");
      out.write("                        <li><a href=\"AboutusLogin.jsp\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"ContactLogin.jsp\">Contact</a></li>\r\n");
      out.write("                        <li><a href=\"Logout\">Logout</a></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                        <h1 style=\"margin-left:380px;\" >Contact Us</h1>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"name\">First Name:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Enter your First Name\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"name\">Last Name:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"text\" placeholder=\"Enter your Last Name\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"name\">Email:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("            \r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"email\" placeholder=\"Enter your Email\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"name\">Contact Number:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                   \r\n");
      out.write("                        <td>\r\n");
      out.write("                            <input type=\"number\" placeholder=\"Enter your Contact Number\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <label for=\"name\">Message:</label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td><textarea style=\"width: 400px; height: 150px;\" name=\"\" id=\"\" placeholder=\"Enter your Queries\"></textarea></td>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </form>\r\n");
      out.write("            </table>\r\n");
      out.write("            <button>Submit</button>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
