/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-07-07 10:15:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class gymequipments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Products</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url(images/productbg.avif);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: 1380px 1000px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ol {\r\n");
      out.write("            background-size: 40px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            display: inline;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: 115px;\r\n");
      out.write("        }\r\n");
      out.write("        li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: aqua;\r\n");
      out.write("            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a:hover {\r\n");
      out.write("            background-color: rgb(53, 61, 53);\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-width: 2px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        img {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .categories {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 550px;\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            color: yellow;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .categ {\r\n");
      out.write("            padding: 30px 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            color: aqua;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .products {\r\n");
      out.write("            width: 950px;\r\n");
      out.write("            height: 550px;\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            margin-left: 320px;\r\n");
      out.write("            margin-top: -557px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .treadmillproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 50px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .treadmillimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .treadmillcontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: -8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            margin-left: 45px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button a{\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: aqua;\r\n");
      out.write("            color: maroon;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .benchpressproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 350px;\r\n");
      out.write("            margin-top: -245px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .benchpressimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .benchpresscontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: -13px;\r\n");
      out.write("        }\r\n");
      out.write("        .stationerybikeproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 650px;\r\n");
      out.write("            margin-top: -245px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stationerybikeimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stationerybikecontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: -25px;\r\n");
      out.write("        }\r\n");
      out.write("        .dumbbellsproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 50px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dumbbellsimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dumbbellscontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: -5px;\r\n");
      out.write("        }\r\n");
      out.write("        .barbellproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 350px;\r\n");
      out.write("            margin-top: -245px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .barbellimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .barbellcontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .punchingbagproduct {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 30px;\r\n");
      out.write("            border: black solid 3px;\r\n");
      out.write("            margin-left: 650px;\r\n");
      out.write("            margin-top: -245px;\r\n");
      out.write("            background-color: rgb(0, 195, 255);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .punchingbagimg {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .punchingbagcontent {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: -15px;\r\n");
      out.write("        }\r\n");
      out.write("        .footer{\r\n");
      out.write("            width: 1270px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .facebook{\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70x;\r\n");
      out.write("            margin-left: 460px;\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .insta{\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70x;\r\n");
      out.write("        }\r\n");
      out.write("        .linkedin{\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70x;\r\n");
      out.write("        }\r\n");
      out.write("        .twitter{\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70x;\r\n");
      out.write("        }\r\n");
      out.write("        .youtube{\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70x;\r\n");
      out.write("        }\r\n");
      out.write("        .navigate{\r\n");
      out.write("            margin-left: 438px;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: blue;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <img src=\"images/249.jpg\" alt=\"\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><a href=\"Home.jsp\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"product.jsp\">Products</a></li>\r\n");
      out.write("                        <li><a href=\"aboutus.jsp\">About us</a></li>\r\n");
      out.write("                        <li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("                        <li><a href=\"login.jsp\">Login</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"adminlogin.jsp\">Admin Login</a></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"categories\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            <center>CATEGORIES\r\n");
      out.write("        </h1>\r\n");
      out.write("        </center>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"categ\">\r\n");
      out.write("            <h2><a style=\"text-decoration: none; color: aqua;\" href=\"product.jsp\">Sports Equipments</a></h2><br><br>\r\n");
      out.write("            <h2><a style=\"text-decoration: none; color: aqua;\" href=\"gymequipments.jsp\">Gym Equipments</a></h2><br><br>\r\n");
      out.write("            <h2><a style=\"text-decoration: none; color: aqua;\" href=\"sportsclothings.jsp\">Sports Clothings</a></h2>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"products\">\r\n");
      out.write("        <div class=\"treadmillproduct\">\r\n");
      out.write("            <img class=\"treadmillimg\" src=\"images/treadmill.avif\">\r\n");
      out.write("            <p class=\"treadmillcontent\">Treadmill Price : Rs 4000</p>\r\n");
      out.write("            <button><a href=\"orderform.jsp\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"benchpressproduct\">\r\n");
      out.write("            <img class=\"benchpressimg\" src=\"images/benchpress.jpg\">\r\n");
      out.write("            <p class=\"benchpresscontent\">Benchpress Price:Rs 3000</p>\r\n");
      out.write("            <button><a href=\"orderform.jsp\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stationerybikeproduct\">\r\n");
      out.write("            <img class=\"stationerybikeimg\" src=\"images/stationerybike.jpg\">\r\n");
      out.write("            <p class=\"stationerybikecontent\">BikeExercise Price: Rs5000</p>\r\n");
      out.write("            <button><a href=\"orderform.jsp\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dumbbellsproduct\">\r\n");
      out.write("            <img class=\"dumbbellsimg\" src=\"images/dumbbells.avif\">\r\n");
      out.write("            <p class=\"dumbbellscontent\">Dumbbells Price: Rs 800</p>\r\n");
      out.write("            <button><a href=\"orderform.jsp\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"barbellproduct\">\r\n");
      out.write("            <img class=\"barbellimg\" src=\"images/barbell.avif\">\r\n");
      out.write("            <p class=\"barbellcontent\">Barbell Price: Rs 1000</p>\r\n");
      out.write("            <button><a href=\"orderform.html\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"punchingbagproduct\">\r\n");
      out.write("            <img class=\"punchingbagimg\" src=\"images/punchingbag.jpg\">\r\n");
      out.write("            <p class=\"punchingbagcontent\">Punchingbag Price:Rs 300</p>\r\n");
      out.write("            <button><a href=\"orderform.html\">Buy Now</a></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><br><br>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <img class=\"facebook\" src=\"images/facebooklogo.avif\" alt=\"\">\r\n");
      out.write("        <img class=\"insta\" src=\"images/instalogo.avif\">\r\n");
      out.write("        <img class=\"linkedin\" src=\"images/linkedinlogo.avif\">\r\n");
      out.write("        <img class=\"twitter\" src=\"images/twitterlogo.avif\">\r\n");
      out.write("        <img class=\"youtube\" src=\"images/youtubelogo.avif\">\r\n");
      out.write("         <div class=\"navigate\">\r\n");
      out.write("            <pre><a href=\"Home.jsp\">Home</a>         <a href=\"contact.jsp\">Contactus</a>          <a href=\"login.jsp\">Login</a>            <a href=\"register.jsp\">Register</a></pre>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
