/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-07-23 10:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\"/>\r\n");
      out.write("    <title>Regis Sports</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-image: url(images/bg.avif);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ol {\r\n");
      out.write("            background-size: 40px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            display: inline;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            margin-left: 110px;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: aqua;\r\n");
      out.write("            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li a:hover {\r\n");
      out.write("            background-color: rgb(53, 61, 53);\r\n");
      out.write("            color: rgb(255, 255, 255);\r\n");
      out.write("            border: black solid;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            border-width: 2px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        img {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("        }\r\n");
      out.write("        .content{\r\n");
      out.write("            margin-left: 100px;\r\n");
      out.write("            margin-top: 60px;\r\n");
      out.write("            width: 700px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("        }\r\n");
      out.write("        h1{\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            font-size: 60px;\r\n");
      out.write("            color: aquamarine;\r\n");
      out.write("            font-family:Verdana, Geneva, Tahoma, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        p{\r\n");
      out.write("            margin-left: 65px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            color: aliceblue;\r\n");
      out.write("        }\r\n");
      out.write("        button{\r\n");
      out.write("            width: 130px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin-left: 265px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            background-color: aqua;\r\n");
      out.write("        }\r\n");
      out.write("        button a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover{\r\n");
      out.write("            background-color: beige;\r\n");
      out.write("        }\r\n");
      out.write("        .gymequip{\r\n");
      out.write("            width: 425px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            background-color: aqua;\r\n");
      out.write("        }\r\n");
      out.write("        .sportsequip{\r\n");
      out.write("            width: 425px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("            margin-top: -400px;\r\n");
      out.write("            background-color:rgb(172, 136, 136);\r\n");
      out.write("        }\r\n");
      out.write("        .sportscloth{\r\n");
      out.write("            width: 425px;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            margin-left: 850px;\r\n");
      out.write("            margin-top: -400px;\r\n");
      out.write("            background-color:aqua;\r\n");
      out.write("        }\r\n");
      out.write("        .gymimg{\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            margin-left: 50px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            box-shadow: 20px 20px 20px black; \r\n");
      out.write("        }\r\n");
      out.write("        .equipbutton{\r\n");
      out.write("            margin-left: 100px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("     .product-section {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("    align-items: flex-start;\r\n");
      out.write("    margin: 50px auto;\r\n");
      out.write("    max-width: 1300px;\r\n");
      out.write("    flex-wrap: wrap; /* Allows wrapping on small screens */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gymequip, .sportsequip, .sportscloth {\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    height: 400px;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    background-color: aqua; /* You can keep individual colors if you want */\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0,0,0,0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .footer{\r\n");
      out.write("            width: 1275px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .footimg{\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            margin-left: 500px;\r\n");
      out.write("        }\r\n");
      out.write("        p a{\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("        .footer{\r\n");
      out.write("            width: 1275px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            background-color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .wrapper{\r\n");
      out.write("            margin-left: 450px;\r\n");
      out.write("            margin-top: 120px;\r\n");
      out.write("        }\r\n");
      out.write("         .navigate{\r\n");
      out.write("            margin-left: 0px;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .quote{\r\n");
      out.write("            font-family:Georgia, 'Times New Roman', Times, serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <img src=\"images/249.jpg\" alt=\"\" href=\"Home.jsp\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <ol>\r\n");
      out.write("                        <li><a href=\"Home.jsp\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"product.jsp\">Products</a></li>\r\n");
      out.write("                        <li><a href=\"aboutus.jsp\">About us</a></li>\r\n");
      out.write("                        <li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("                        <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("                        <li><a href=\"adminlogin.jsp\">Admin Login</a></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"content\"><center>\r\n");
      out.write("        <h1>REGIS SPORTS</h1>\r\n");
      out.write("        </center>\r\n");
      out.write("        <p class=\"quote\" style=\"margin-left: 10px;\">YOU'LL NEVER EXPERIENCE UNLESS YOU TRY</p>\r\n");
      out.write("        <p style=\"margin-left: 245px;\"> SINCE 2003'</p>\r\n");
      out.write("        <button><a href=\"product.jsp\">Products</a></button>\r\n");
      out.write("    </div><br><br><br>\r\n");
      out.write("   <div class=\"product-section\">\r\n");
      out.write("    <div class=\"gymequip\">\r\n");
      out.write("        <img class=\"gymimg\" src=\"images/gymequiments.avif\" alt=\"\">\r\n");
      out.write("        <h2><button class=\"equipbutton\"><a href=\"gymequipments.jsp\">Gym Equipments</a></button></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sportsequip\">\r\n");
      out.write("        <img class=\"gymimg\" src=\"images/sportsequipments.avif\" alt=\"\">\r\n");
      out.write("        <h2><button class=\"equipbutton\"><a href=\"product.jsp\">Sports Equipments</a></button></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sportscloth\">\r\n");
      out.write("        <img class=\"gymimg\" src=\"images/sportsclothings.avif\" alt=\"\">\r\n");
      out.write("        <h2><button class=\"equipbutton\"><a href=\"sportsclothings.jsp\">Sports Clothings</a></button></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Facebook</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Twitter</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Instagram</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-github\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>Github</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">\r\n");
      out.write("           <div class=\"icon\">\r\n");
      out.write("              <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("           </div>\r\n");
      out.write("           <span>YouTube</span>\r\n");
      out.write("        </a><br><br><br><br>\r\n");
      out.write("        <div class=\"navigate\">\r\n");
      out.write("            <pre><a href=\"Home.jsp\">Home</a>         <a href=\"contact.jsp\">Contactus</a>          <a href=\"login.jsp\">Login</a>            <a href=\"register.jsp\">Register</a></pre>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
